### ISSUE TITLE
Issue when dividing by 0.

### ISSUE THREAD

**Issue by jonatan-holmgren** [pwndd/Calculator#1]
```
Traceback (most recent call last):
  File "/home/jonte/calculator.py", line 29, in <module>
    print(str(num1) + ' / ' + str(num2) + ' = ' + str(divide(num1, num2)))
  File "/home/jonte/calculator.py", line 10, in divide
    return x / y
ZeroDivisionError: division by zero
```

**Comment by jonatan-holmgren** [comment]
I fixed your stolen code.
